### ISSUE TITLE
宿主机ssh登录vm(ubuntu/vbox)并且vm可以联网

### ISSUE THREAD

**Issue by gougoushan** [gougoushan/code-snippet#18]
1、添加两个虚拟网卡，分别为NAT和Host-Only链接模式，NAT可以让VM连接网络，Host-Only让宿主机可以链接VM
2、编辑 /etc/netplan/00-installer-config.yaml
```yaml
network:
  ethernets:
    enp0s3:
      dhcp4: true
      nameservers:
        addresses: [114.114.114.114, 8.8.8.8]
    enp0s8:
      dhcp4: false
      addresses: [192.168.56.100/24]
  version: 2
```
参考：https://beamtic.com/virtualbox-host-only-and-nat
